services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flarum1-app
    restart: always
    environment:
      APP_URL: http://16.16.159.159:8000
      DB_HOST: db
      DB_NAME: flarum
      DB_USER: flarum
      DB_PASS: secret
    volumes:
      - flarum_data:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/http.d/default.conf # if using single container Nginx/PHP
    depends_on:
      - db

volumes:
  flarum_data:
